---
- name: Instalar Suricata y dependencias
  apt:
    name: 
      - suricata
      - jq
      - python3-pip
    state: present
    update_cache: yes

- name: Detener Suricata para configurar
  service:
    name: suricata
    state: stopped

- name: Optimizar Interfaz de Monitoreo (Desactivar Offloading)
  shell: |
    ethtool -K {{ sniff_interface }} gro off lro off tso off gso off
  ignore_errors: yes

- name: Habilitar modo promiscuo en la interfaz de monitoreo
  shell: |
    ip link set dev {{ sniff_interface }} promisc on && ip link set dev {{ sniff_interface }} up
  ignore_errors: yes
  # Esto asegura que Suricata vea los paquetes originales, no "reensamblados" por la NIC.

### Configuración de Suricata
- name: Configurerar HOME_NET
  replace:
    path: /etc/suricata/suricata.yaml
    regexp: 'HOME_NET: "\[[^"]+\]"'
    replace: 'HOME_NET: "[{{ home_net }}]"'

- name: Configurar la interfaz de monitoreo
  replace:
    path: /etc/suricata/suricata.yaml
    regexp: 'interface: .+'
    replace: 'interface: {{ sniff_interface }}'

- name: Actualizar reglas de Suricata (ET Open)
  command: suricata-update
  register: update_result
  changed_when: "'No changes' not in update_result.stdout"

- name: Programar actualización diaria de reglas Suricata a las 05:00
  cron:
    name: "Actualizar reglas Suricata"
    minute: "0"
    hour: "5"
    user: root
    job: "/usr/bin/suricata-update >/var/log/suricata-update.log 2>&1"
    state: present

- name: Asegurar que Suricata inicie al boot
  service:
    name: suricata
    enabled: yes
    state: started

- name: Configurar interfaz de captura
  copy:
    dest: /etc/systemd/system/promisc-interface.service
    content: |
      [Unit]
      Description=Preparar interfaz {{ sniff_interface }} para Suricata
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/usr/sbin/ip link set dev {{ sniff_interface }} up
      ExecStart=/usr/sbin/ip link set dev {{ sniff_interface }} promisc on
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target

- name: Habilitar servicio promisc
  systemd:
    name: promisc-interface
    enabled: yes
    state: started

