[wazuh_nodes]
# Nombre_VM ansible_host=IP_fija_de_tofu
wazuh-master ansible_host=192.168.100.45

[sensor_nodes]
sensor-01 ansible_host=192.168.100.46

[ansible_host]
Puppet-Master ansible_host=192.168.100.47

[all:vars]
# Usuario por defecto de la imagen Ubuntu Cloud
ansible_user=chaha
# Ruta a la llave privada que generó tu script de setup
ansible_ssh_private_key_file=~/.ssh/puppet_master_ed25519
# Evitar errores de "Known Hosts" en despliegues nuevos
ansible_ssh_common_args='-o StrictHostKeyChecking=no'