---
# site.yml - Master Playbook para Chahã

## 1. PREPARACIÓN GLOBAL
- name: Preparar dependencias en todos los nodos
  hosts: all
  become: yes
  tasks:
    - name: Actualizar cache de APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

# Certificates generation
- hosts: aio
  roles:
    - role: roles/wazuh-ansible/roles/wazuh/wazuh-indexer
      perform_installation: false
  become: no
  #become_user: root
  vars:
    indexer_node_master: true
    instances:
      node1:
        name: node-1       # Important: must be equal to indexer_node_name.
        ip: 127.0.0.1
        role: indexer
  tags:
    - generate-certs

# Single node
- name: Deploy Wazuh All-in-One
  hosts: aio
  become: yes
  become_user: root
  roles:
    - role: roles/wazuh-ansible/roles/wazuh/wazuh-indexer
    - role: roles/wazuh-ansible/roles/wazuh/ansible-wazuh-manager
    - role: roles/wazuh-ansible/roles/wazuh/ansible-filebeat-oss
    - role: roles/wazuh-ansible/roles/wazuh/wazuh-dashboard
  vars:
    single_node: true
    minimum_master_nodes: 1
    indexer_node_master: true
    indexer_network_host: 127.0.0.1
    filebeat_node_name: node-1
    filebeat_output_indexer_hosts: 
    - 127.0.0.1
    instances:
      node1:
        name: node-1       # Important: must be equal to indexer_node_name.
        ip: 127.0.0.1
        role: indexer
    ansible_shell_allow_world_readable_temp: true


## 3. DESPLIEGUE DE SENSORES (IDS/NSM)

- name: Deploy Suricata (IDS)
  hosts: sensor_nodes
  become: yes
  roles:
    - role: suricata

- name: Deploy Zeek (NSM)
  hosts: sensor_nodes
  become: yes
  roles:
    - role: zeek

- name: Deploy Wazuh Agents (Sensors)
  hosts: sensor_nodes
  become: yes
  roles:
    - role: wazuh-agent

- name: Deploy Wazuh Manager Configuration
  hosts: aio
  become: yes
  roles:
    - role: wazuh-manager-conf

## 4. VERIFICACIÓN FINAL
- name: Resumen del despliegue
  hosts: wazuh_nodes
  become: yes
  tasks:
    - name: Mostrar ubicación de contraseñas
      debug:
        msg: "El despliegue ha finalizado. Puedes encontrar las contraseñas del Dashboard en /root/wazuh-passwords.txt en el servidor Master."
